source:      .
destination: ./_site
includes:    ./_includes
url: "https://nelebru.github.io"
baseurl: ""


collections:
  projects:
    output: true
  recipes:
    output: true

plugins:
  - jekyll-sitemap
